// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJZTvbJUf_K_tKPVEWtS0pGKJHtFJGN4I',
    appId: '1:261052600551:web:f919d0f3ed089320435242',
    messagingSenderId: '261052600551',
    projectId: 'webtruyen-1c107',
    authDomain: 'webtruyen-1c107.firebaseapp.com',
    databaseURL: 'https://webtruyen-1c107-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webtruyen-1c107.firebasestorage.app',
    measurementId: 'G-PNEQSTS73W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsCTFD74t4p38QcKkcpPcd19tWwKu-8OQ',
    appId: '1:261052600551:android:3f31342dcff06c2f435242',
    messagingSenderId: '261052600551',
    projectId: 'webtruyen-1c107',
    databaseURL: 'https://webtruyen-1c107-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webtruyen-1c107.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5GTRXXJ2oVHf517N6eA44AtUEPJ8gtGE',
    appId: '1:261052600551:ios:81e33a16ee8a7319435242',
    messagingSenderId: '261052600551',
    projectId: 'webtruyen-1c107',
    databaseURL: 'https://webtruyen-1c107-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webtruyen-1c107.firebasestorage.app',
    iosBundleId: 'com.example.truyentranhmauCuoiki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5GTRXXJ2oVHf517N6eA44AtUEPJ8gtGE',
    appId: '1:261052600551:ios:81e33a16ee8a7319435242',
    messagingSenderId: '261052600551',
    projectId: 'webtruyen-1c107',
    databaseURL: 'https://webtruyen-1c107-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webtruyen-1c107.firebasestorage.app',
    iosBundleId: 'com.example.truyentranhmauCuoiki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJZTvbJUf_K_tKPVEWtS0pGKJHtFJGN4I',
    appId: '1:261052600551:web:ad46e81dda43a166435242',
    messagingSenderId: '261052600551',
    projectId: 'webtruyen-1c107',
    authDomain: 'webtruyen-1c107.firebaseapp.com',
    databaseURL: 'https://webtruyen-1c107-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webtruyen-1c107.firebasestorage.app',
    measurementId: 'G-30M4R78T7B',
  );
}
